description: "The default job for G2 ruby projects"
parameters:
  bundler-version:
    description: "The Bundler version to install"
    type: string
    default: ""
  test-reporter-tag:
    description: "The tag for the CodeClimate test reporter to download"
    type: string
    default: "latest"
  additional-tests:
    description: The steps to run for the additional rspec
    type: steps
    default: []
  elasticsearch:
    description: "The `elasticsearch` Docker image version tag."
    type: string
    default: "7.8.0"
  postgres:
    description: "The `postgres` Docker image version tag."
    type: string
    default: "latest"
  psql:
    description: "Does psql need to be installed"
    type: boolean
    default: false
  psql-version:
    description: "What version of PostgreSQL Client needs to be installed?"
    type: string
    default: postgresql-client-12
  setup-database:
    description: "Do we need to run database migrations?"
    type: boolean
    default: true
  redis:
    description: "The `redis` Docker image version"
    type: string
    default: "latest"
  ruby:
    description: "The `cimg/ruby` Docker image version tag."
    type: string
    default: "latest"
  project-dir:
    description: "The project directory path for monorepo setup."
    type: string
    default: "."
  default-branch:
    default: main
    description: "The name of the default github branch."
    type: string
  pattern:
    default: .*
    description: >
      The regex to match files against. The command uses grep to search file
      names.
      If you want to enforce starting with use ^. For checking if files in src/
      or lib/ were modified,
      the pattern to use would be ^src.*|^lib.*
    type: string
executor:
  name: default
  ruby: << parameters.ruby >>
  redis: << parameters.redis >>
  postgres: << parameters.postgres >>
  elasticsearch: << parameters.elasticsearch >>
working_directory: ~/project/<< parameters.project-dir >>
steps:
  - checkout
  - swissknife/run_if_modified:
      always-run-on-branch: << parameters.default-branch >>
      base-branch: << parameters.default-branch >>
      pattern: << parameters.pattern >>
      steps-to-run:
        - load-cache
        - install-deps:
            bundler-version: << parameters.bundler-version >>
        - save-cache
        - when:
            condition: << parameters.setup-database >>
            steps:
              - setup-database:
                  psql: << parameters.psql >>
                  psql-version: << parameters.psql-version >>
        - install-cc-test-reporter:
            tag: << parameters.test-reporter-tag >>
        - cc-before-build
        - run-tests:
            additional-tests: << parameters.additional-tests >>
        - cc-after-build
